### ISSUE TITLE
Add filesystem-watch-service

### ISSUE THREAD

**Issue by thespain** [theforeman/puppet-puppet#549] opened 2017-09-14 12:32 UTC
Hello,

After upgrading puppetserver and related packages from 5.0.1 to 5.1.0 I found that the `puppetserver` service would not start with the following error in the puppet server log:

```bash
2017-09-14 07:40:42,300 INFO  [main] [o.e.j.u.log] Logging initialized @12162ms to org.eclipse.jetty.util.log.Slf4jLog
2017-09-14 07:40:44,306 ERROR [main] [p.t.internal] Error during app buildup!
java.lang.RuntimeException: Service ':FilesystemWatchService' not found
        at puppetlabs.trapperkeeper.internal$handle_prismatic_exception_BANG_.invokeStatic(internal.clj:121)
        at puppetlabs.trapperkeeper.internal$handle_prismatic_exception_BANG_.invoke(internal.clj:111)
        at puppetlabs.trapperkeeper.internal$instantiate$fn__13800.invoke(internal.clj:162)
        at puppetlabs.trapperkeeper.internal$instantiate.invokeStatic(internal.clj:159)
        at puppetlabs.trapperkeeper.internal$instantiate.invoke(internal.clj:152)
        at puppetlabs.trapperkeeper.internal$eval14334$build_app_STAR___14343$fn__14344.invoke(internal.clj:569)
        at puppetlabs.trapperkeeper.internal$eval14334$build_app_STAR___14343.invoke(internal.clj:537)
        at puppetlabs.trapperkeeper.internal$eval14436$boot_services_STAR___14445$fn__14446$fn__14447.invoke(internal.
clj:639)
        at puppetlabs.trapperkeeper.internal$eval14436$boot_services_STAR___14445$fn__14446.invoke(internal.clj:638)
        at puppetlabs.trapperkeeper.internal$eval14436$boot_services_STAR___14445.invoke(internal.clj:633)
        at puppetlabs.trapperkeeper.core$eval15266$boot_with_cli_data__15273$fn__15274.invoke(core.clj:130)
        at puppetlabs.trapperkeeper.core$eval15266$boot_with_cli_data__15273.invoke(core.clj:95)
        at puppetlabs.trapperkeeper.core$eval15295$run__15300$fn__15301.invoke(core.clj:151)
        at puppetlabs.trapperkeeper.core$eval15295$run__15300.invoke(core.clj:145)
        at puppetlabs.trapperkeeper.core$main.invokeStatic(core.clj:173)
        at puppetlabs.trapperkeeper.core$main.doInvoke(core.clj:159)
        at clojure.lang.RestFn.invoke(RestFn.java:512)
        at clojure.lang.Var.invoke(Var.java:409)
        at clojure.lang.AFn.applyToHelper(AFn.java:178)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.core$apply.invoke(core.clj:641)
        at puppetlabs.trapperkeeper.main$_main.invokeStatic(main.clj:7)
        at puppetlabs.trapperkeeper.main$_main.doInvoke(main.clj:4)
        at clojure.lang.RestFn.invoke(RestFn.java:512)
        at clojure.lang.Var.invoke(Var.java:409)
        at clojure.lang.AFn.applyToHelper(AFn.java:178)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.core$apply.invokeStatic(core.clj:646)
        at clojure.main$main_opt.invokeStatic(main.clj:314)
        at clojure.main$main_opt.invoke(main.clj:310)
        at clojure.main$main.invokeStatic(main.clj:421)
        at clojure.main$main.doInvoke(main.clj:384)
        at clojure.lang.RestFn.invoke(RestFn.java:619)
        at clojure.lang.Var.invoke(Var.java:430)
        at clojure.lang.AFn.applyToHelper(AFn.java:195)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
2017-09-14 07:40:44,311 INFO  [Thread-2] [p.t.internal] Shutting down due to JVM shutdown hook.
2017-09-14 07:40:44,314 INFO  [Thread-2] [p.t.internal] Beginning shutdown sequence
2017-09-14 07:40:44,323 INFO  [Thread-2] [p.t.internal] Finished shutdown sequence
```

After adding the following line into `/etc/puppetlabs/puppetserver/services.d/ca.cfg`, then the service was able to successfully start (which I found was the only change in ca.cfg.rpmnew).
`puppetlabs.trapperkeeper.services.watcher.filesystem-watch-service/filesystem-watch-service`

Can this service be added into the `ca.cfg` template?

Thanks,
Jake

**Comment by ekohl** [comment] 2017-09-14 12:33
Does https://github.com/theforeman/puppet-puppet/pull/548 fix your issue?

**Comment by thespain** [comment] 2017-09-14 14:22
I temporarily added the branch `ps_510` from that PR to my Puppetfile and it no longer whacks that line.

However, it looks like there are some changes in the module that required me to also add `puppetlabs-hocon` and `puppetlabs-puppet_authorization` to my environment. As a result, a noop run reports that it will make the following changes, so I just want to investigate/test these further before letting the agent run (I was previously using theforeman-puppet version 8.0.0 on the forge):

```bash
Notice: /Stage[main]/Puppet::Server::Puppetserver/Hocon_setting[metrics.server-id]/value: current_value ['localhost'], should be ['_redacted sensative_'] (noop)
Notice: /Stage[main]/Puppet::Server::Puppetserver/Hocon_setting[metrics.registries.puppetserver.reporters.graphite.enabled]/ensure: current_value 'absent', should be 'present' (noop)
Notice: /Stage[main]/Puppet::Server::Puppetserver/Hocon_setting[metrics.reporters.graphite.host]/ensure: current_value 'absent', should be 'present' (noop)
Notice: /Stage[main]/Puppet::Server::Puppetserver/Hocon_setting[metrics.reporters.graphite.port]/ensure: current_value 'absent', should be 'present' (noop)
Notice: /Stage[main]/Puppet::Server::Puppetserver/Hocon_setting[metrics.reporters.graphite.update-interval-seconds]/ensure: current_value 'absent', should be 'present' (noop)
Notice: /Stage[main]/Puppet::Server::Puppetserver/Puppet_authorization::Rule[puppetlabs catalog]/Puppet_authorization_hocon_rule[rule-puppetlabs catalog]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Puppet_authorization::Rule[puppetlabs catalog]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Puppet::Server::Puppetserver/Puppet_authorization::Rule[puppetlabs certificate]/Puppet_authorization_hocon_rule[rule-puppetlabs certificate]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Puppet_authorization::Rule[puppetlabs certificate]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Puppet::Server::Puppetserver/Puppet_authorization::Rule[puppetlabs crl]/Puppet_authorization_hocon_rule[rule-puppetlabs crl]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Puppet_authorization::Rule[puppetlabs crl]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Puppet::Server::Puppetserver/Puppet_authorization::Rule[puppetlabs csr]/Puppet_authorization_hocon_rule[rule-puppetlabs csr]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Puppet_authorization::Rule[puppetlabs csr]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Puppet::Server::Puppetserver/Puppet_authorization::Rule[puppetlabs environments]/Puppet_authorization_hocon_rule[rule-puppetlabs environments]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Puppet_authorization::Rule[puppetlabs environments]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Puppet::Server::Puppetserver/Puppet_authorization::Rule[puppetlabs environment classes]/Puppet_authorization_hocon_rule[rule-puppetlabs environment classes]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Puppet_authorization::Rule[puppetlabs environment classes]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Puppet::Server::Puppetserver/Puppet_authorization::Rule[puppetlabs node]/Puppet_authorization_hocon_rule[rule-puppetlabs node]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Puppet_authorization::Rule[puppetlabs node]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Puppet::Server::Puppetserver/Puppet_authorization::Rule[puppetlabs report]/Puppet_authorization_hocon_rule[rule-puppetlabs report]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Puppet_authorization::Rule[puppetlabs report]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Puppet::Server::Puppetserver/Puppet_authorization::Rule[puppetlabs status]/Puppet_authorization_hocon_rule[rule-puppetlabs status]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Puppet_authorization::Rule[puppetlabs status]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Puppet::Server::Puppetserver/Puppet_authorization::Rule[puppetlabs static file content]/Puppet_authorization_hocon_rule[rule-puppetlabs static file content]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Puppet_authorization::Rule[puppetlabs static file content]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Puppet::Server::Puppetserver/Puppet_authorization::Rule[environment-cache]/Puppet_authorization_hocon_rule[rule-environment-cache]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Puppet_authorization::Rule[environment-cache]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Puppet::Server::Puppetserver/Puppet_authorization::Rule[jruby-pool]/Puppet_authorization_hocon_rule[rule-jruby-pool]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Puppet_authorization::Rule[jruby-pool]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Puppet::Server::Puppetserver/Puppet_authorization::Rule[puppetlabs deny all]/Puppet_authorization_hocon_rule[rule-puppetlabs deny all]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Puppet_authorization::Rule[puppetlabs deny all]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Puppet::Server::Puppetserver/Puppet_authorization::Rule[certificate_status]/Puppet_authorization_hocon_rule[rule-certificate_status]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Puppet_authorization::Rule[certificate_status]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Puppet::Server::Puppetserver/Puppet_authorization::Rule[certificate_statuses]/Puppet_authorization_hocon_rule[rule-certificate_statuses]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Puppet_authorization::Rule[certificate_statuses]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Puppet::Server::Puppetserver/Puppet_authorization::Rule[puppetlabs file bucket file]/Puppet_authorization_hocon_rule[rule-puppetlabs file bucket file]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Puppet_authorization::Rule[puppetlabs file bucket file]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Puppet::Server::Puppetserver/Puppet_authorization::Rule[puppetlabs file content]/Puppet_authorization_hocon_rule[rule-puppetlabs file content]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Puppet_authorization::Rule[puppetlabs file content]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Puppet::Server::Puppetserver/Puppet_authorization::Rule[puppetlabs file metadata]/Puppet_authorization_hocon_rule[rule-puppetlabs file metadata]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Puppet_authorization::Rule[puppetlabs file metadata]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Puppet::Server::Puppetserver/Puppet_authorization::Rule[puppetlabs experimental]/Puppet_authorization_hocon_rule[rule-puppetlabs experimental]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Puppet_authorization::Rule[puppetlabs experimental]: Would have triggered 'refresh' from 1 event
Notice: /Stage[main]/Puppet::Server::Puppetserver/Puppet_authorization::Rule[puppet tasks information]/Puppet_authorization_hocon_rule[rule-puppet tasks information]/ensure: current_value 'absent', should be 'present' (noop)
Notice: Puppet_authorization::Rule[puppet tasks information]: Would have triggered 'refresh' from 1 event
Notice: Class[Puppet::Server::Puppetserver]: Would have triggered 'refresh' from 25 events

```

Thanks

**Comment by mmoll** [comment] 2017-09-14 14:23
I'll backport this to 8.0.x...

**Comment by mmoll** [comment] 2017-09-14 14:56
@thespain please test #550

**Comment by mmoll** [comment] 2017-09-14 16:06
fixed in current master, 8.0-stable and released 8.0.3 :bowtie:

**Closed** 2017-09-14 16:06 UTC

**Comment by thespain** [comment] 2017-09-14 16:08
@mmoll, I tried branch `ps_510_80`, verified by running the agent at least twice and looks good. The only other change this time was to `auth.conf`, which I dont see a problem with adding task info:

```bash
Notice: /Stage[main]/Puppet::Server::Puppetserver/File[/etc/puppetlabs/puppetserver/conf.d/auth.conf]/content: 
--- /etc/puppetlabs/puppetserver/conf.d/auth.conf	2017-07-14 13:45:27.228820896 -0400
+++ /tmp/puppet-file20170914-11662-miy08w	2017-09-14 11:57:47.544132380 -0400
@@ -200,6 +200,15 @@
             name: "puppetlabs static file content"
         },
         {
+            match-request: {
+                path: "/puppet/v3/tasks"
+                type: path
+            }
+            allow: "*"
+            sort-order: 500
+            name: "puppet tasks information"
+        },
+        {
             # Allow all users access to the experimental endpoint
             # which currently only provides a dashboard web ui.
             match-request: {

Notice: /Stage[main]/Puppet::Server::Puppetserver/File[/etc/puppetlabs/puppetserver/conf.d/auth.conf]/content: current_value '{md5}c8cdff11b0ee6e85befc9dc36f210e97', should be '{md5}b159f634abcde5a154ff81696b688535' (noop)
```

**Comment by mmoll** [comment] 2017-09-14 16:12
yes, that's expected 👍

**Comment by mc-hack** [comment] 2018-03-28 20:41
oops --- it did it again:

Debian Stretch 9.4
puppetserver 5.1.3-1stretch
foreman-installer 1.16.0~rc2-1

my workaround was to remove the last if statement  in 
`/usr/share/foreman-installer/modules/puppet/templates/server/puppetserver/services.d/ca.cfg.erb`  
to force the line  
`puppetlabs.trapperkeeper.services.watcher.filesystem-watch-service/filesystem-watch-service` 
being finally enabled in 
`/etc/puppetlabs/puppetserver/services.d/ca.cfg` 

I've to do this BEFORE foreman-installer runs first time! to change this after the first run direct in ca.cfg doesnt work well -- it leads to other problems like "no smart proxy ... blabla".

maybe the versioncmp should be more general for 5.1.**x** versions of puppetserver?

**Comment by mmoll** [comment] 2018-03-28 21:21
what's the exact puppet version?

**Comment by mc-hack** [comment] 2018-03-28 21:29
```

dpkg -l | grep puppet
ii  foreman-installer                     1.16.0-1                                all          Automated puppet-based installer for The Foreman
ii  puppet-agent                          5.5.0-1stretch                          amd64        The Puppet Agent package contains all of the elements needed to run puppet, including ruby, facter, hiera and mcollective.
ii  puppet-agent-oauth                    0.5.1-2                                 all          OAuth Core Ruby implementation for Puppet Agent
ii  puppet5-release                       5.0.0-1stretch                          all          Release packages for the Puppet5 repository
ii  puppetlabs-release-pc1                1.1.0-5stretch                          all          Release packages for the Puppet Labs PC1 repository
ii  puppetserver                          5.3.0-1stretch                          all          no description given
ii  ruby-kafo                             2.0.2-1                                 all          Ruby gem for making installations based on puppet user friendly
```

**Comment by mmoll** [comment] 2018-03-28 22:00
I can't reproduce this on a fresh Debian 9.4 VM:
```
[...]
Setting up ruby-kafo (2.0.2-1) ...
Setting up foreman-installer (1.16.0-1) ...
Processing triggers for libc-bin (2.24-11+deb9u3) ...
root@eula-fordyce:~# foreman-installer 
Installing  Done  [100%] [......................................................]
  Success!
[...]
root@eula-fordyce:~# puppet agent --test
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Caching catalog for eula-fordyce.kvedulv.de
Info: Applying configuration version '1522274250'
Notice: Applied catalog in 0.09 seconds
root@eula-fordyce:~# cat /etc/puppetlabs/puppetserver/services.d/ca.cfg
# To enable the CA service, leave the following line uncommented
puppetlabs.services.ca.certificate-authority-service/certificate-authority-service
# To disable the CA service, comment out the above line and uncomment the line below
#puppetlabs.services.ca.certificate-authority-disabled-service/certificate-authority-disabled-service
puppetlabs.trapperkeeper.services.watcher.filesystem-watch-service/filesystem-watch-service
root@eula-fordyce:~# dpkg -l | egrep '(puppet|foreman|kafo|openjdk)'
ii  foreman                        1.16.0-1                                amd64        Systems management web interface
ii  foreman-cli                    1.16.0-1                                all          metapackage providing hammer CLI for Foreman
ii  foreman-debug                  1.16.0-1                                all          provides support utility foreman-debug.
ii  foreman-installer              1.16.0-1                                all          Automated puppet-based installer for The Foreman
ii  foreman-postgresql             1.16.0-1                                all          metapackage providing PostgreSQL dependencies for Foreman
ii  foreman-proxy                  1.16.0-1                                all          RESTful proxies for DNS, DHCP, TFTP, and Puppet
ii  openjdk-8-jre-headless:amd64   8u162-b12-1~deb9u1                      amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
ii  puppet-agent                   5.5.0-1stretch                          amd64        The Puppet Agent package contains all of the elements needed to run puppet, including ruby, facter, hiera and mcollective.
ii  puppet-agent-oauth             0.5.1-2                                 all          OAuth Core Ruby implementation for Puppet Agent
ii  puppet5-release                5.0.0-1stretch                          all          Release packages for the Puppet5 repository
ii  puppetserver                   5.3.0-1stretch                          all          no description given
ii  ruby-foreman-setup             5.0.0-1                                 all          Foreman Setup Plugin
ii  ruby-hammer-cli-foreman        0.11.0-1                                all          Foreman commands for Hammer
ii  ruby-kafo                      2.0.2-1                                 all          Ruby gem for making installations based on puppet user friendly
ii  ruby-kafo-parsers              0.1.6-1                                 all          Puppet module parsers
ii  ruby-kafo-wizards              0.0.1-1                                 all          Wizard like interfaces in terminal
```

**Comment by mc-hack** [comment] 2018-03-29 09:00
Okay. My "fresh" Debian is from an older template (9.1), dist-upgraded to 9.4 before installation of foreman-installer etc. 

Maybe thats not fresh enough for the foreman-installer. "fresh install" is a bit far from my reality as well. Initially I'd like to add the remote-excecution plugin to a exiting foreman server -- no chance. 

I'll try again to find the difference as soon as possible...

**Comment by mmoll** [comment] 2018-03-29 14:08
@mc-hack Was this installation updated from Puppetserver 5.0?

If yes, the installer answers were cached in `/etc/foreman-installer/scenarios.d/foreman-answers.yaml` and you can use `foreman-installer --reset-puppet-server-puppetserver-version` to "recalculate" that parameter (there might be more parameters that need resetting, but looking again onto my old PR, that one should suffice).
