### ISSUE TITLE
wheezy-backports (3.7.2) and jessie (3.8.5) agents cannot retrieve certificates from a stretch (4.8) puppet master

### ISSUE THREAD

**Issue by dlucredativ** [theforeman/puppet-puppet#578] opened 2018-02-12 18:39 UTC
Depending on how to interpret the Changelog [1] for 8.0.0 and whether the 8.0-stable is still maintained, commit 11e4c4 introduced a bug for new wheezy-backports & jessie puppet agents. When a fresh agent requests the puppet master's CA certificate, a 406 HTTPNotAcceptableError is thrown in response_formatter_for().
This is because the agent sends "Accept: s",  the puppet master expects "Accept: s", but the config.ru as shipped since 11e4c4 rewrites the header to "Accept: binary".

[1] * Drop Puppet 3 support in the module code. Having Puppet 3 agents configured by a Puppet 4 server still works.

**Comment by mmoll** [comment] 2018-02-12 19:06
@sathieu could you have a look? ☝️

**Comment by sathieu** [comment] 2018-02-16 10:52
I'm able to reproduce the issue:
```
Warning: Error 403 on SERVER: Forbidden request: <master> access to /certificate_revocation_list/ca [find] at :125
```

The accept handling is similar too [the one in PuppetServer](https://github.com/puppetlabs/puppetserver/blob/ff0e5e84860ea9b035839e77e9b27d4c3a923e36/src/clj/puppetlabs/services/legacy_routes/legacy_routes_core.clj#L22-L42)). But it should not be called on all request. It's hard for me to read the clojure code to extract the conditions...

**Comment by dlucredativ** [comment] 2018-09-04 14:10
I would say that the conditions are defined by the various "def self.supported_formats".

puppet 3.7.2:
```
file_serving/content.rb:  def self.supported_formats
file_serving/content.rb-    [:raw]
file_serving/content.rb-  end
--
transaction/report.rb:  def self.supported_formats
transaction/report.rb-    [:pson, :yaml]
transaction/report.rb-  end
--
file_bucket/file.rb:  def self.supported_formats
file_bucket/file.rb-    [:s, :pson]
file_bucket/file.rb-  end
--
ssl/certificate_revocation_list.rb:  def self.supported_formats
ssl/certificate_revocation_list.rb-    [:s]
ssl/certificate_revocation_list.rb-  end
--
ssl/certificate_request.rb:  def self.supported_formats
ssl/certificate_request.rb-    [:s]
ssl/certificate_request.rb-  end
--
ssl/key.rb:  def self.supported_formats
ssl/key.rb-    [:s]
ssl/key.rb-  end
--
ssl/certificate.rb:  def self.supported_formats
ssl/certificate.rb-    [:s]
ssl/certificate.rb-  end
```
puppet 4.8.2:
```
file_bucket/file.rb:  def self.supported_formats
file_bucket/file.rb-    [:binary]
file_bucket/file.rb-  end
--
file_serving/content.rb:  def self.supported_formats
file_serving/content.rb-    [:binary]
file_serving/content.rb-  end
--
ssl/certificate.rb:  def self.supported_formats
ssl/certificate.rb-    [:s]
ssl/certificate.rb-  end
--
ssl/certificate_request.rb:  def self.supported_formats
ssl/certificate_request.rb-    [:s]
ssl/certificate_request.rb-  end
--
ssl/certificate_revocation_list.rb:  def self.supported_formats
ssl/certificate_revocation_list.rb-    [:s]
ssl/certificate_revocation_list.rb-  end
--
ssl/key.rb:  def self.supported_formats
ssl/key.rb-    [:s]
ssl/key.rb-  end
--
transaction/report.rb:  def self.supported_formats
transaction/report.rb-    [:pson, :yaml]
transaction/report.rb-  end
```

As I understand, the supported_formats are used for both agent and master, so the 3.7.2 file_bucket/file "s, pson" does not match the 4.8.2 "binary" without a rewrite. It seems that the old condition for a "binary" rewrite was almost correct:
```
if @api =~ /^file_(content|bucket_file)/ && @req.get?
  env["HTTP_ACCEPT"] = "binary"
```
Almost, because the request type for file_bucket_file is HEAD or PUT:
```
+19724:5b8e811c:7a|HEAD /production/file_bucket_file/md5/e07910a06a086c83ba41827aa00b26ed//tmp/testfile HTTP/1.1|Accept:s, pson|Accept-Encoding:identity|User-Agent:Ruby|Host:a5fa786b3c8c%3a8140
+19724:5b8e811c:7b|PUT /production/file_bucket_file/md5/e07910a06a086c83ba41827aa00b26ed//tmp/testfile HTTP/1.1|Accept:s, pson|Accept-Encoding:identity|Content-Type:text/plain|User-Agent:Ruby|Host:a5fa786b3c8c%3a8140|Content-Length:4
```

**Comment by dlucredativ** [comment] 2018-09-04 14:35
The following snippet seems to work in the context of this issue as well as of bugs.debian.org/869183
```
    if @api =~ /^file_(content|bucket_file)/
      env["HTTP_ACCEPT"] = "binary"
      env["CONTENT_TYPE"] = "application/octet-stream"
    end
```

**Comment by mmoll** [comment] 2018-12-15 22:47
@dlucredativ would you open a PR to the 10.1-stable branch? Otherwise I'd close this one due to GH-650

**Comment by sathieu** [comment] 2018-12-16 16:18
Hello,

Sorry for this late reply. I've changed job and I no longer use Puppet (I'm using salt now), and I no longer use Foreman either (but I hope this will change in the future).

Cheers.

(@mmol, I've taked over your ruby-vcr package in Debian as you might have seen).

**Comment by mmoll** [comment] 2018-12-17 13:59
@dlucredativ "The clojure variant"? As far as I understood this problem, it only occurs when using the rack based puppetmaster as server?

**Comment by dlucredativ** [comment] 2018-12-17 14:04
11e4c4 refers to https://bugs.debian.org/869183 in which one can find the statement:
```
The attached patch fixes this and matches the behavior of:
https://github.com/puppetlabs/puppetserver/blob/ff0e5e84860ea9b035839e77e9b27d4c3a923e36/src/clj/puppetlabs/services/legacy_routes/legacy_routes_core.clj#L27-L42
```

So I guess a non-passenger setup is affected as well.

**Comment by sathieu** [comment] 2018-12-17 15:47
The clojure variant is the reference implementation and works AFAICT. The bug only affects rack based puppet master.

**Comment by ekohl** [comment] 2018-12-17 16:20
We can't control puppetserver since it's all compiled so it needs to be patches in the used apt repository. I'm leaning to closing this so we can move forward with puppetserver only.

**Comment by mmoll** [comment] 2019-01-04 15:15
closing...

**Closed by mmoll** 2019-01-04 15:15 UTC
Labels: Bug
