### ISSUE TITLE
stdlib deprications

### ISSUE THREAD

**Issue by james-powis** [theforeman/puppet-puppet#470] opened 2017-01-10 19:41 UTC
```
  Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Bool. There is further documentation for validate_legacy function in the README.
     (at C:/ProgramData/PuppetLabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
  Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Hash. There is further documentation for validate_legacy function in the README.
     (at C:/ProgramData/PuppetLabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
  Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::String. There is further documentation for validate_legacy function in the README.
     (at C:/ProgramData/PuppetLabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
  Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Array. There is further documentation for validate_legacy function in the README.
     (at C:/ProgramData/PuppetLabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
  Warning: This method is deprecated, please use the stdlib validate_legacy function, with Stdlib::Compat::Absolute_Path. There is further documentation for validate_legacy function in the README.
     (at C:/ProgramData/PuppetLabs/code/environments/production/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
```

**Comment by ekohl** [comment] 2017-01-11 11:26
The problem is that we still want to maintain Puppet 3 compatibility. Sadly [validate_legacy](https://github.com/puppetlabs/puppetlabs-stdlib#validate_legacy) is only compatible with Puppet 4.4.0 and higher. Currently I don't see another solution than accepting the deprecation warnings.

**Comment by mmoll** [comment] 2017-04-08 19:49
should be fixed in current master.

**Closed by mmoll** 2017-04-08 19:49 UTC
